title: "wgs_prism2 Sequence Production and QC Report"
subtitle: "Run: 230923_A01439_0214_AHGG2WDSX7"


custom_logo: "resources/AgR-Colour.jpg"
custom_logo_title: "AgResearch"
custom_logo_url: "https://www.agresearch.co.nz"


report_header_info:
  - Contact E-mail: "ben.perry@agresearch.co.nz"
  - Application Type: "Illumina TruSeq RNA from FFPE-Derived RNA input"
  - Sequencing Platform: "NovaSeq 6000"
  - Sequencing Setup: "2 Lanes @ 2x151 - L001 & L002"


ignore_images: false


module_order:
  - bclconvert
  - fastqc:
      name: "FastQC of Raw Sequencing Reads"
      anchor: "fastqc_raw"
      path_filters:
        - "*001_fastqc*"
  - bbduk
  - bowtie2:
      name: "Bowtie2 Alignment to SILVA138 Ribosomal rRNA Database"
      anchor: "SILVA138"
      path_filters: 
        - "*.DS.R*.bowtie2.log"
  - fastqc:
      name: "FastQC of bbduk Trimmed and SILVA Filtered Reads"
      anchor: "fastqc_trimmed"
      path_filters:
        - "*bbduk_silva_fastqc*"
  - bowtie2:
      name: "Bowtie2 Alignment to GRCh38"
      anchor: "GRCh38"
      path_filters: 
        - "*.genome_alignment.bowtie2.R*.log"
  - kraken


kraken:
  top_n: 50


section_comments:
  bclconvert: "This section summarises the reports generated by Illumina bcl-convert during sequence production."
  fastqc: "This section of the report shows FastQC results for fastq data."
  bbduk: "BBDuk - Trimming adapters, poly-G tails, and  filtering for reads >10 bp."
  bowtie2: "Alignment of 1 million subsampled reads against SILVA138.1 ribosomal rRNA Database or GRCh38 reference humand genome."
  kraken: "Taxonomic composition of 1 million subsampled reads using the prebuilt NCBI-nt Kraken2 index (release: 11/29/2023; https://benlangmead.github.io/aws-indexes/k2)."
